# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoUserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelUser = QtWidgets.QLabel(self.centralwidget)
        self.labelUser.setGeometry(QtCore.QRect(50, 90, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelUser.setFont(font)
        self.labelUser.setObjectName("labelUser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 140, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditAccountNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAccountNumber.setEnabled(False)
        self.lineEditAccountNumber.setGeometry(QtCore.QRect(190, 150, 471, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAccountNumber.setFont(font)
        self.lineEditAccountNumber.setObjectName("lineEditAccountNumber")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditCurrentBalance = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCurrentBalance.setEnabled(False)
        self.lineEditCurrentBalance.setGeometry(QtCore.QRect(190, 210, 471, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditCurrentBalance.setFont(font)
        self.lineEditCurrentBalance.setObjectName("lineEditCurrentBalance")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 280, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 340, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEditSenderNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSenderNumber.setEnabled(True)
        self.lineEditSenderNumber.setGeometry(QtCore.QRect(200, 350, 471, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditSenderNumber.setFont(font)
        self.lineEditSenderNumber.setObjectName("lineEditSenderNumber")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 400, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEditReceiverNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditReceiverNumber.setEnabled(True)
        self.lineEditReceiverNumber.setGeometry(QtCore.QRect(200, 410, 471, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditReceiverNumber.setFont(font)
        self.lineEditReceiverNumber.setObjectName("lineEditReceiverNumber")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 460, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEditAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAmount.setEnabled(True)
        self.lineEditAmount.setGeometry(QtCore.QRect(140, 470, 341, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAmount.setFont(font)
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.pushButtonSend = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend.setGeometry(QtCore.QRect(540, 450, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 515, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        UserWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UserWindow)
        self.statusbar.setObjectName("statusbar")
        UserWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "User:"))
        self.labelUser.setText(_translate("UserWindow", "User:"))
        self.label.setText(_translate("UserWindow", "Account number:"))
        self.label_3.setText(_translate("UserWindow", "Current balance:"))
        self.label_4.setText(_translate("UserWindow", "Transfers"))
        self.label_5.setText(_translate("UserWindow", "Bank of a changing world"))
        self.label_6.setText(_translate("UserWindow", "Sender number:"))
        self.label_7.setText(_translate("UserWindow", "Receiver number:"))
        self.label_8.setText(_translate("UserWindow", "Amount:"))
        self.pushButtonSend.setText(_translate("UserWindow", "Send"))
